version: "3.8"
name: "inception"
services:
  mariadb:
    build:
      context: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    container_name: mariadb
    restart: always
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx/.
    volumes:
      - wordpress:/var/www/wordpress
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ebouvier/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ebouvier/data/mariadb'

networks:
  inception:
    driver: bridge
